services:

  telegram:
    image: ghcr.io/arian-nj/tix-bot:${GIT_COMMIT_HASH}
    build:
      context: .
      dockerfile: bot.Dockerfile

    environment:
      - RELEASE_BOT_TOKEN=8122683105:AAHIVYGHFjgb0DCv1SHQYjv30Wg3olsnnxI
      - RELEASE_DATABASE_URL=postgres://pgadmin:sdoi32dfEF03Rf3f3g@db:5432/game?sslmode=disable
      - RELEASE_MODE=release

    deploy:
      update_config:
        order: start-first

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: mq90rcqnuc38crn
      POSTGRES_DB: game
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Keeps data persistent
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

