services:
  reverse-proxy:
    image: traefik:v3.3
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=filelord01@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--api=true"
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.chigame.site`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.routers.traefik.service=api@internal"
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  
  frontend:
    image: ghcr.io/arian-nj/chi-game:${GIT_COMMIT_HASH}
    build:
      context: .
      dockerfile: front.Dockerfile

    environment:
      - RELEASE_MODE=release

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.core_api.loadbalancer.server.port=3000"
      - "traefik.http.routers.core_api.rule=Host(`chigame.site`)"
      - "traefik.http.routers.core_api.entrypoints=websecure"
      - "traefik.http.routers.core_api.tls.certresolver=myresolver"

  backend:
    image: ghcr.io/arian-nj/chi-game:${GIT_COMMIT_HASH}
    build:
      context: .
      dockerfile: back.Dockerfile

    environment:
      - RELEASE_BOT_TOKEN=8452814311:AAGPKXzHy3Fs2anmoG5abDNmPIBDYedHSVY
      - RELEASE_DATABASE_URL=postgres://pgadmin:p239ijfw921ioad@db:5432/game?sslmode=disable
      - RELEASE_MODE=release

    deploy:
      update_config:
        order: start-first

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.core_api.loadbalancer.server.port=8383"
      - "traefik.http.routers.core_api.rule=Host(`api.chigame.site`)"
      - "traefik.http.routers.core_api.entrypoints=websecure"
      - "traefik.http.routers.core_api.tls.certresolver=myresolver"



  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: p239ijfw921ioad
      POSTGRES_DB: game
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Keeps data persistent
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  letsencrypt:
