// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: game_sessions.sql

package database

import (
	"context"
)

const countGameSessions = `-- name: CountGameSessions :one
Select Count(*) from game_sessions
`

func (q *Queries) CountGameSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countGameSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLastDayHubs = `-- name: CountLastDayHubs :one
SELECT COUNT(*) AS games_today
FROM game_sessions
WHERE created_at >= date_trunc('day', NOW())
`

func (q *Queries) CountLastDayHubs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastDayHubs)
	var games_today int64
	err := row.Scan(&games_today)
	return games_today, err
}

const countLastHourHub = `-- name: CountLastHourHub :one
SELECT COUNT(*) AS hubs_last_hour
FROM game_sessions
WHERE created_at >= NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountLastHourHub(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastHourHub)
	var hubs_last_hour int64
	err := row.Scan(&hubs_last_hour)
	return hubs_last_hour, err
}

const createGameSession = `-- name: CreateGameSession :one
INSERT INTO game_sessions DEFAULT VALUES RETURNING id, created_at
`

func (q *Queries) CreateGameSession(ctx context.Context) (GameSession, error) {
	row := q.db.QueryRow(ctx, createGameSession)
	var i GameSession
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
