// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: hubs.sql

package database

import (
	"context"
)

const countHubs = `-- name: CountHubs :one
Select Count(*) from hubs
`

func (q *Queries) CountHubs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countHubs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLastDayHubs = `-- name: CountLastDayHubs :one
SELECT COUNT(*) AS hubs_today
FROM hubs
WHERE created_at >= date_trunc('day', NOW())
`

func (q *Queries) CountLastDayHubs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastDayHubs)
	var hubs_today int64
	err := row.Scan(&hubs_today)
	return hubs_today, err
}

const countLastHourHub = `-- name: CountLastHourHub :one
SELECT COUNT(*) AS hubs_last_hour
FROM hubs
WHERE created_at >= NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountLastHourHub(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastHourHub)
	var hubs_last_hour int64
	err := row.Scan(&hubs_last_hour)
	return hubs_last_hour, err
}

const createHub = `-- name: CreateHub :one
INSERT INTO hubs (game_type, tg_id) VALUES ($1, $2) RETURNING id, created_at, game_type, tg_id
`

type CreateHubParams struct {
	GameType string
	TgID     int
}

func (q *Queries) CreateHub(ctx context.Context, arg CreateHubParams) (Hub, error) {
	row := q.db.QueryRow(ctx, createHub, arg.GameType, arg.TgID)
	var i Hub
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GameType,
		&i.TgID,
	)
	return i, err
}
