// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GameSession struct {
	ID        int
	CreatedAt pgtype.Timestamp
}

type Person struct {
	ID        int
	Coins     int32
	CreatedAt pgtype.Timestamp
}

type TelegramUser struct {
	ID        int
	TgID      int
	PersonID  pgtype.Int8
	IsActive  pgtype.Bool
	UpdatedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}
