// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Hub struct {
	ID        int
	CreatedAt pgtype.Timestamp
	GameType  string
	TgID      int
}

type User struct {
	ID        int
	TgID      int
	CreatedAt pgtype.Timestamp
	IsActive  pgtype.Bool
	UpdatedAt pgtype.Timestamp
}
