// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: person.sql

package database

import (
	"context"
)

const createPerson = `-- name: CreatePerson :one
INSERT INTO persons DEFAULT VALUES RETURNING id, coins, created_at
`

func (q *Queries) CreatePerson(ctx context.Context) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson)
	var i Person
	err := row.Scan(&i.ID, &i.Coins, &i.CreatedAt)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, coins, created_at FROM persons
WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id int) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(&i.ID, &i.Coins, &i.CreatedAt)
	return i, err
}
