// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_games.sql

package database

import (
	"context"
)

const createSessionGame = `-- name: CreateSessionGame :one
INSERT INTO session_games (session_id,game_type) VALUES ($1,$2) RETURNING id, session_id, game_type, started_at, ended_at, status
`

type CreateSessionGameParams struct {
	SessionID int
	GameType  string
}

func (q *Queries) CreateSessionGame(ctx context.Context, arg CreateSessionGameParams) (SessionGame, error) {
	row := q.db.QueryRow(ctx, createSessionGame, arg.SessionID, arg.GameType)
	var i SessionGame
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.GameType,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
	)
	return i, err
}
