// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const activeUser = `-- name: ActiveUser :exec
UPDATE users SET is_active = TRUE
WHERE (
  tg_id = $1
)
`

func (q *Queries) ActiveUser(ctx context.Context, tgID int) error {
	_, err := q.db.Exec(ctx, activeUser, tgID)
	return err
}

const countAllUsers = `-- name: CountAllUsers :many
SELECT COUNT(*) FROM users
`

func (q *Queries) CountAllUsers(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, countAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users
    (tg_id)
SELECT  $1
WHERE
    NOT EXISTS (
        SELECT id FROM users WHERE tg_id=$1
    )
`

func (q *Queries) CreateUser(ctx context.Context, tgID int) error {
	_, err := q.db.Exec(ctx, createUser, tgID)
	return err
}

const diactiveUser = `-- name: DiactiveUser :exec
UPDATE users SET is_active = FALSE
WHERE (
  tg_id = $1
)
`

func (q *Queries) DiactiveUser(ctx context.Context, tgID int) error {
	_, err := q.db.Exec(ctx, diactiveUser, tgID)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, tg_id, created_at, is_active, updated_at FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TgID,
			&i.CreatedAt,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, tg_id, created_at, is_active, updated_at FROM users
WHERE tg_id = $1
`

func (q *Queries) GetUser(ctx context.Context, tgID int) (User, error) {
	row := q.db.QueryRow(ctx, getUser, tgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.CreatedAt,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersStatic = `-- name: GetUsersStatic :one
SELECT
  COUNT(*) FILTER (WHERE is_active = TRUE) AS active_users,
  COUNT(*) AS total_users,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 day') AS users_created_last_24_hours,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '7 days') AS users_created_last_week,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 month') AS users_created_last_month
FROM users
`

type GetUsersStaticRow struct {
	ActiveUsers             int64
	TotalUsers              int64
	UsersCreatedLast24Hours int64
	UsersCreatedLastWeek    int64
	UsersCreatedLastMonth   int64
}

func (q *Queries) GetUsersStatic(ctx context.Context) (GetUsersStaticRow, error) {
	row := q.db.QueryRow(ctx, getUsersStatic)
	var i GetUsersStaticRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.TotalUsers,
		&i.UsersCreatedLast24Hours,
		&i.UsersCreatedLastWeek,
		&i.UsersCreatedLastMonth,
	)
	return i, err
}

const updateMixedUserStatuses = `-- name: UpdateMixedUserStatuses :exec
UPDATE users
SET is_active = CASE
  WHEN id = ANY ($1::bigint[]) THEN TRUE
  ELSE FALSE  
END
`

func (q *Queries) UpdateMixedUserStatuses(ctx context.Context, dollar_1 []int) error {
	_, err := q.db.Exec(ctx, updateMixedUserStatuses, dollar_1)
	return err
}
