// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTgUsers = `-- name: CountActiveTgUsers :one
SELECT COUNT(*) FROM telegram_users
WHERE is_active = TRUE
`

func (q *Queries) CountActiveTgUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTgUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTgUsers = `-- name: CountAllTgUsers :one
SELECT COUNT(*) FROM telegram_users
`

func (q *Queries) CountAllTgUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTgUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersTgCreatedBetween = `-- name: CountUsersTgCreatedBetween :one
SELECT COUNT(*) FROM telegram_users
WHERE created_at >= $1 AND created_at <= $2
`

type CountUsersTgCreatedBetweenParams struct {
	CreatedAt   pgtype.Timestamp
	CreatedAt_2 pgtype.Timestamp
}

func (q *Queries) CountUsersTgCreatedBetween(ctx context.Context, arg CountUsersTgCreatedBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersTgCreatedBetween, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTgUser = `-- name: CreateTgUser :one
INSERT INTO telegram_users (tg_id) VALUES ($1) ON
	CONFLICT (tg_id) DO UPDATE
	SET updated_at = NOW(), is_active = TRUE RETURNING id, tg_id, created_at, is_active, updated_at
`

func (q *Queries) CreateTgUser(ctx context.Context, tgID int) (TelegramUser, error) {
	row := q.db.QueryRow(ctx, createTgUser, tgID)
	var i TelegramUser
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.CreatedAt,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllTgUsers = `-- name: GetAllTgUsers :many
SELECT id, tg_id, created_at, is_active, updated_at FROM telegram_users
`

func (q *Queries) GetAllTgUsers(ctx context.Context) ([]TelegramUser, error) {
	rows, err := q.db.Query(ctx, getAllTgUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelegramUser
	for rows.Next() {
		var i TelegramUser
		if err := rows.Scan(
			&i.ID,
			&i.TgID,
			&i.CreatedAt,
			&i.IsActive,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTgUser = `-- name: GetTgUser :one
SELECT id, tg_id, created_at, is_active, updated_at FROM telegram_users
WHERE tg_id = $1
`

func (q *Queries) GetTgUser(ctx context.Context, tgID int) (TelegramUser, error) {
	row := q.db.QueryRow(ctx, getTgUser, tgID)
	var i TelegramUser
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.CreatedAt,
		&i.IsActive,
		&i.UpdatedAt,
	)
	return i, err
}

const getTgUsersStatic = `-- name: GetTgUsersStatic :one
SELECT
  COUNT(*) FILTER (WHERE is_active = TRUE) AS active_users,
  COUNT(*) AS total_users,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 day') AS users_created_last_24_hours,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '7 days') AS users_created_last_week,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 month') AS users_created_last_month
FROM telegram_users
`

type GetTgUsersStaticRow struct {
	ActiveUsers             int64
	TotalUsers              int64
	UsersCreatedLast24Hours int64
	UsersCreatedLastWeek    int64
	UsersCreatedLastMonth   int64
}

func (q *Queries) GetTgUsersStatic(ctx context.Context) (GetTgUsersStaticRow, error) {
	row := q.db.QueryRow(ctx, getTgUsersStatic)
	var i GetTgUsersStaticRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.TotalUsers,
		&i.UsersCreatedLast24Hours,
		&i.UsersCreatedLastWeek,
		&i.UsersCreatedLastMonth,
	)
	return i, err
}

const updateMixedTgUserStatuses = `-- name: UpdateMixedTgUserStatuses :exec

UPDATE telegram_users
SET is_active = CASE
  WHEN id = ANY ($1::bigint[]) THEN TRUE
  ELSE FALSE  
END
`

// -- name: ActiveTgUser :exec
// UPDATE telegram_users SET is_active = TRUE
// WHERE (
//
//	tg_id = $1
//
// );
//
// -- name: DiactiveTgUser :exec
// UPDATE telegram_users SET is_active = FALSE
// WHERE (
//
//	tg_id = $1
//
// );
func (q *Queries) UpdateMixedTgUserStatuses(ctx context.Context, dollar_1 []int) error {
	_, err := q.db.Exec(ctx, updateMixedTgUserStatuses, dollar_1)
	return err
}
