// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: persons.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTgUsers = `-- name: CountActiveTgUsers :one
SELECT COUNT(*) FROM persons
WHERE is_active = TRUE
`

func (q *Queries) CountActiveTgUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTgUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTgUsers = `-- name: CountAllTgUsers :one
SELECT COUNT(*) FROM persons
`

func (q *Queries) CountAllTgUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTgUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersTgCreatedBetween = `-- name: CountUsersTgCreatedBetween :one
SELECT COUNT(*) FROM persons
WHERE created_at >= $1 AND created_at <= $2
`

type CountUsersTgCreatedBetweenParams struct {
	CreatedAt   pgtype.Timestamp
	CreatedAt_2 pgtype.Timestamp
}

func (q *Queries) CountUsersTgCreatedBetween(ctx context.Context, arg CountUsersTgCreatedBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersTgCreatedBetween, arg.CreatedAt, arg.CreatedAt_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTgUser = `-- name: CreateTgUser :one
INSERT INTO persons (tg_id,name)
VALUES ($1,$2)
ON CONFLICT (tg_id) DO UPDATE
SET updated_at = NOW(),
    is_active = TRUE
RETURNING id, tg_id, name, is_active, updated_at, created_at
`

type CreateTgUserParams struct {
	TgID int
	Name string
}

func (q *Queries) CreateTgUser(ctx context.Context, arg CreateTgUserParams) (Person, error) {
	row := q.db.QueryRow(ctx, createTgUser, arg.TgID, arg.Name)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.Name,
		&i.IsActive,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAllTgUsers = `-- name: GetAllTgUsers :many
SELECT id, tg_id, name, is_active, updated_at, created_at FROM persons
`

func (q *Queries) GetAllTgUsers(ctx context.Context) ([]Person, error) {
	rows, err := q.db.Query(ctx, getAllTgUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.TgID,
			&i.Name,
			&i.IsActive,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTgUserByID = `-- name: GetTgUserByID :one
SELECT id, tg_id, name, is_active, updated_at, created_at FROM persons
WHERE id = $1
`

func (q *Queries) GetTgUserByID(ctx context.Context, id int) (Person, error) {
	row := q.db.QueryRow(ctx, getTgUserByID, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.Name,
		&i.IsActive,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTgUserByTgID = `-- name: GetTgUserByTgID :one
SELECT id, tg_id, name, is_active, updated_at, created_at FROM persons
WHERE tg_id = $1
`

func (q *Queries) GetTgUserByTgID(ctx context.Context, tgID int) (Person, error) {
	row := q.db.QueryRow(ctx, getTgUserByTgID, tgID)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.Name,
		&i.IsActive,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTgUsersStatic = `-- name: GetTgUsersStatic :one
SELECT
  COUNT(*) FILTER (WHERE is_active = TRUE) AS active_users,
  COUNT(*) AS total_users,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 day') AS users_created_last_24_hours,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '7 days') AS users_created_last_week,
  COUNT(*) FILTER ( WHERE created_at >= NOW() - INTERVAL '1 month') AS users_created_last_month
FROM persons
`

type GetTgUsersStaticRow struct {
	ActiveUsers             int64
	TotalUsers              int64
	UsersCreatedLast24Hours int64
	UsersCreatedLastWeek    int64
	UsersCreatedLastMonth   int64
}

func (q *Queries) GetTgUsersStatic(ctx context.Context) (GetTgUsersStaticRow, error) {
	row := q.db.QueryRow(ctx, getTgUsersStatic)
	var i GetTgUsersStaticRow
	err := row.Scan(
		&i.ActiveUsers,
		&i.TotalUsers,
		&i.UsersCreatedLast24Hours,
		&i.UsersCreatedLastWeek,
		&i.UsersCreatedLastMonth,
	)
	return i, err
}

const updateMixedTgUserStatuses = `-- name: UpdateMixedTgUserStatuses :exec

UPDATE persons
SET is_active = CASE
  WHEN id = ANY ($1::bigint[]) THEN TRUE
  ELSE FALSE  
END
`

// -- name: ActiveTgUser :exec
// UPDATE persons SET is_active = TRUE
// WHERE (
//
//	tg_id = $1
//
// );
//
// -- name: DiactiveTgUser :exec
// UPDATE persons SET is_active = FALSE
// WHERE (
//
//	tg_id = $1
//
// );
func (q *Queries) UpdateMixedTgUserStatuses(ctx context.Context, dollar_1 []int) error {
	_, err := q.db.Exec(ctx, updateMixedTgUserStatuses, dollar_1)
	return err
}
