// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package database

import (
	"context"
)

const countLastDaySessions = `-- name: CountLastDaySessions :one
SELECT COUNT(*) AS games_today
FROM sessions
WHERE created_at >= date_trunc('day', NOW())
`

func (q *Queries) CountLastDaySessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastDaySessions)
	var games_today int64
	err := row.Scan(&games_today)
	return games_today, err
}

const countLastHourHub = `-- name: CountLastHourHub :one
SELECT COUNT(*) AS hubs_last_hour
FROM sessions
WHERE created_at >= NOW() - INTERVAL '1 hour'
`

func (q *Queries) CountLastHourHub(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLastHourHub)
	var hubs_last_hour int64
	err := row.Scan(&hubs_last_hour)
	return hubs_last_hour, err
}

const countSessions = `-- name: CountSessions :one
Select Count(*) from sessions
`

func (q *Queries) CountSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (createdMode) VALUES ($1) RETURNING id, createdmode, created_at
`

func (q *Queries) CreateSession(ctx context.Context, createdmode string) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, createdmode)
	var i Session
	err := row.Scan(&i.ID, &i.Createdmode, &i.CreatedAt)
	return i, err
}
