// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_players.sql

package database

import (
	"context"
)

const createSessionPlayer = `-- name: CreateSessionPlayer :one
INSERT INTO session_players (session_id,person_id) VALUES ($1,$2) RETURNING id, session_id, person_id
`

type CreateSessionPlayerParams struct {
	SessionID int
	PersonID  int
}

func (q *Queries) CreateSessionPlayer(ctx context.Context, arg CreateSessionPlayerParams) (SessionPlayer, error) {
	row := q.db.QueryRow(ctx, createSessionPlayer, arg.SessionID, arg.PersonID)
	var i SessionPlayer
	err := row.Scan(&i.ID, &i.SessionID, &i.PersonID)
	return i, err
}
