// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_messages.sql

package database

import (
	"context"
)

const createSessionMessage = `-- name: CreateSessionMessage :one
INSERT INTO session_messages (session_id,player_id,message) VALUES ($1,$2,$3) RETURNING id, session_id, player_id, message, sent_at
`

type CreateSessionMessageParams struct {
	SessionID int
	PlayerID  int
	Message   string
}

func (q *Queries) CreateSessionMessage(ctx context.Context, arg CreateSessionMessageParams) (SessionMessage, error) {
	row := q.db.QueryRow(ctx, createSessionMessage, arg.SessionID, arg.PlayerID, arg.Message)
	var i SessionMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PlayerID,
		&i.Message,
		&i.SentAt,
	)
	return i, err
}

const getSessionMessages = `-- name: GetSessionMessages :many
SELECT id, session_id, player_id, message, sent_at
FROM session_messages
WHERE session_id = $1
ORDER BY id DESC
LIMIT $2
`

type GetSessionMessagesParams struct {
	SessionID int
	Limit     int32
}

func (q *Queries) GetSessionMessages(ctx context.Context, arg GetSessionMessagesParams) ([]SessionMessage, error) {
	rows, err := q.db.Query(ctx, getSessionMessages, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionMessage
	for rows.Next() {
		var i SessionMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PlayerID,
			&i.Message,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
