name: release pipeline
on:
  workflow_dispatch:
    inputs:
      project_version:
        description: 'Project version tag (e.g., 1.2.3)'
        required: true
        type: string

run-name: "Game Release - ${{ inputs.project_version }}"

permissions:
  packages: write
  contents: read

jobs:
  build_and_push_back_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.read_token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Bot Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: back.Dockerfile
          tags: |
            ghcr.io/arian-nj/chi-core-api:latest
            ghcr.io/arian-nj/chi-core-api:${{ github.sha }}

  build_and_push_front_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.read_token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Bot Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: front.Dockerfile
          tags: |
            ghcr.io/arian-nj/chi-front:latest
            ghcr.io/arian-nj/chi-front:${{ github.sha }}



  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build_and_push_back_image
      - build_and_push_front_image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token:  ${{ secrets.read_token }}

      - name: create env file
        run: |
            echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
            echo "PROJECT_VERSION=${{ inputs.project_version }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: chi-game
          file: docker-stack.yaml
          host:  144.172.91.193
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile

          registry_auth: true
          registry_host: 'ghcr.io'
          registry_user: ${{ secrets.GHCR_USER }}
          registry_pass: ${{ secrets.GHCR_TOKEN }}
          summary: true

